### PR TITLE
Livechat Widget: Fix auto-scroll

### LINKED ISSUE #446: [2] Auto advance text in widget window
text in the widget window should automatically advance to the end - user may have to scroll up to see something that went past, but should never have to scroll down to read.

### PR DESCRIPTION
**Pull request by Kailash0311**
Closes [#446](https://github.com/WideChat/Rocket.Chat/issues/446)

### CODE REVIEW

File: src/components/Messages/MessageList/index.js [hunk 1]
```diff
@@ -116,6 +116,14 @@ export class MessageList extends MemoizedComponent {
 			}
 			delete this.previousScrollHeight;
 		}
+
+		// when scrollPosition is "free", scroll to bottom
+		if (this.scrollPosition == "free") {
```
Comment (Shailesh351) [inline src/components/Messages/MessageList/index.js]:
```suggestion
		if (this.scrollPosition === MessageList.SCROLL_FREE) {
```

Other things looks good to me

**Review by Shailesh351 — APPROVED** [review]
